#!/usr/bin/env python3
"""
Setup script for configuring Polymarket API keys.
Guides the user through secure API key configuration.
"""

import os
import sys
from pathlib import Path
from getpass import getpass


def main():
    """Interactive setup for API keys."""
    print("=" * 60)
    print("🔑 Polymarket Bot - API Key Setup")
    print("=" * 60)
    print()
    print("This script will help you configure your Polymarket API credentials.")
    print()
    print("⚠️  IMPORTANT:")
    print("   - Never commit your .env file to git")
    print("   - Keep your private key secure")
    print("   - Use paper trading mode for testing")
    print()

    # Check if .env already exists
    env_path = Path(__file__).parent.parent / ".env"

    if env_path.exists():
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("❌ Setup cancelled")
            return

    print("\n📝 Enter your Polymarket credentials:")
    print()

    # Get API key
    api_key = input("Polymarket API Key: ").strip()
    if not api_key:
        print("❌ API key is required")
        sys.exit(1)

    # Get private key (hidden input)
    print("\n⚠️  Your private key will be hidden as you type")
    private_key = getpass("Polymarket Private Key (0x...): ").strip()
    if not private_key:
        print("❌ Private key is required")
        sys.exit(1)

    # Validate private key format
    if not private_key.startswith("0x"):
        print("⚠️  Private key should start with '0x'. Adding it automatically...")
        private_key = "0x" + private_key

    # Get trading mode
    print("\n💰 Select trading mode:")
    print("  1. Paper Trading (recommended for testing)")
    print("  2. Live Trading (real money)")
    mode = input("Enter choice (1 or 2): ").strip()

    paper_trading = mode != "2"

    if not paper_trading:
        print("\n⚠️  WARNING: You selected LIVE TRADING mode")
        confirm = input("Type 'CONFIRM' to proceed with live trading: ").strip()
        if confirm != "CONFIRM":
            print("❌ Live trading not confirmed. Using paper trading mode.")
            paper_trading = True

    # Trading parameters
    print("\n📊 Configure trading parameters:")

    max_position = input("Max position size in USD (default: 5.0): ").strip()
    if not max_position:
        max_position = "5.0"

    max_positions = input("Max open positions (default: 3): ").strip()
    if not max_positions:
        max_positions = "3"

    target_asset = input("Target asset (bitcoin/ethereum/solana/xrp, default: bitcoin): ").strip()
    if not target_asset:
        target_asset = "bitcoin"

    # Create .env file
    env_content = f"""# Polymarket Bot Configuration
# Generated by setup_api_keys.py

# Polymarket API Credentials
POLYMARKET_API_KEY={api_key}
POLYMARKET_PRIVATE_KEY={private_key}

# Trading Mode
PAPER_TRADING={'true' if paper_trading else 'false'}

# Trading Parameters
MAX_POSITION_SIZE={max_position}
MAX_OPEN_POSITIONS={max_positions}
MAX_TOTAL_EXPOSURE={float(max_position) * float(max_positions)}
TARGET_ASSET={target_asset}

# Strategy Parameters
MIN_CONFIDENCE=0.80
MAX_CONFIDENCE=0.95
MIN_EXPECTED_EDGE=0.10
MIN_TIME_REMAINING=60
MAX_TIME_REMAINING=180

# Bot Settings
SCAN_INTERVAL_SECONDS=10
DEBUG=false
"""

    # Write .env file
    with open(env_path, 'w') as f:
        f.write(env_content)

    # Set secure permissions
    os.chmod(env_path, 0o600)

    print("\n" + "=" * 60)
    print("✅ API keys configured successfully!")
    print("=" * 60)
    print(f"\n📁 Configuration saved to: {env_path}")
    print(f"🔒 File permissions set to: 600 (owner read/write only)")
    print(f"💰 Trading mode: {'📝 Paper Trading' if paper_trading else '💵 Live Trading'}")
    print(f"💵 Max position size: ${max_position}")
    print(f"📊 Max open positions: {max_positions}")
    print(f"🎯 Target asset: {target_asset.upper()}")
    print()
    print("🚀 You can now run the bot with:")
    print("   python -m src.bot")
    print()
    print("⚠️  Remember:")
    print("   - Start with paper trading to test")
    print("   - Monitor the bot closely when live")
    print("   - Never share your private key")
    print("=" * 60)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
